name: DEACoastlines

channels:
    - anaconda-fusion
    - conda-forge
    - defaults

dependencies:
    - aiohttp
    - aiosignal
    - argon2-cffi
    - argon2-cffi-bindings
    - asttokens
    - async-timeout
    - attrs
    - backcall
    - bleach
    - boto3
    - botocore
    - bottleneck
    - branca
    - cachetools
    - certifi
    - cffi
    - cftime
    - charset-normalizer
    - ciso8601
    - click
    - click-plugins
    - cligj
    - cloudpickle
    - cycler
    - dask[array]
    - dask-image
    - datacube[performance,s3]
    - debugpy
    - decorator
    - defusedxml
    - distributed
    - entrypoints
    - executing
    - fiona
    - folium
    - fonttools
    - frozenlist
    - fsspec
    - gdal
    - geographiclib
    - geopandas
    - geopy
    - greenlet
    - heapdict
    - idna
    - imageio
    - importlib-resources
    - ipykernel
    - ipyleaflet
    - ipython
    - ipywidgets
    - jedi
    - jinja2
    - jmespath
    - joblib
    - jsonschema
    - jupyter-ui-poll
    - kiwisolver
    - lark-parser
    - locket
    - lxml
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mistune
    - multidict
    - munch
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - netcdf4
    - networkx
    - notebook
    - numexpr
    - numpy
    - odc-algo
    - odc-geo
    - owslib
    - packaging
    - pandas
    - pandocfilters
    - parso
    - partd
    - pexpect
    - pickleshare
    - pillow
    - pims
    - prompt-toolkit
    - psutil
    - psycopg2
    - ptyprocess
    - pycparser
    - pygeos
    - pygments
    - pyparsing
    - pyproj
    - pyrsistent
    - python-dateutil
    - python-geohash
    - pytmd
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - rasterio
    - rasterstats
    - requests
    - s3transfer
    - scikit-image
    - scikit-learn
    - scipy
    - send2trash
    - setuptools-scm
    - shapely
    - simplejson
    - six
    - slicerator
    - snuggs
    - sortedcontainers
    - sqlalchemy
    - tblib
    - terminado
    - testpath
    - threadpoolctl
    - tifffile
    - tomli
    - toolz
    - tornado
    - tqdm
    - traitlets
    - traittypes
    - typing-extensions
    - urllib3
    - wcwidth
    - webencodings
    - widgetsnbextension
    - xarray
    - xyzservices
    - yarl
    - zict
    - zipp
    - pip:
        - stack-data
        - jupyterlab-widgets
        - dea-tools
        - prometheus-client
        - msgpack
        - ipython-genutils
        - jupyterlab-pygments
        - jupyter-core
        - jupyter-client
        - pure-eval
        - odc-ui
